/*------------------------------------------------------------------------
    File        : Interface2
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : Mike
    Created     : Fri Apr 12 11:10:30 CEST 2013
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.
USING Consultingwerk.InterfaceSample.Interface1.

INTERFACE Consultingwerk.InterfaceSample.Interface2 INHERITS Interface1:  
  
    METHOD PUBLIC VOID MethodFromInterface2 ().
       
  
END INTERFACE.