/*------------------------------------------------------------------------
    File        : Interface1
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : Mike
    Created     : Fri Apr 12 11:09:10 CEST 2013
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

INTERFACE Consultingwerk.InterfaceSample.Interface1:  
  
    METHOD PUBLIC VOID MethodFromInterface1 ().
   
  
END INTERFACE.