/*------------------------------------------------------------------------
    File        : Interface3
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : Mike
    Created     : Fri Apr 12 11:11:07 CEST 2013
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

INTERFACE Consultingwerk.InterfaceSample.Interface3:  
  
    METHOD PUBLIC VOID MethodFromInterface3 ().
  
END INTERFACE.