class rssw.SimpleObject:
  define public property prop01 as longchar get. set.

  constructor SimpleObject() :
    // Nothing
  end constructor.

  /**
   * Method #1
   */
  method public void method1(xxx as integer  ) :
    // Nothing
  end.

  method public void method1(xxx as integer, yyy as integer) :
    // Nothing
  end.

  method public void method2(xxx as integer, yyy as integer) :
    // Nothing
  end.

end class.
